"""링크 선수 명단 이관 상수 — 2026-07-31 사용자 확정 분류 (스펙 §7).

category · transfer_status 는 사람 확정 값이다.
운영 중 변경은 DB 가 SoT 이고, 이 상수는 이관 · 로컬 부트스트랩 · 테스트 스텁용으로만 쓴다.
"""

ROSTER: list[dict] = [
    {"full_name": "Mikel Arteta", "first_name": "Mikel", "surname": "Arteta",
     "ko_name": "아르테타", "club": "Arsenal",
     "category": "manager", "transfer_status": "none"},
    {"full_name": "Bukayo Saka", "first_name": "Bukayo", "surname": "Saka",
     "ko_name": "사카", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "William Saliba", "first_name": "William", "surname": "Saliba",
     "ko_name": "살리바", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Declan Rice", "first_name": "Declan", "surname": "Rice",
     "ko_name": "라이스", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Martin Odegaard", "first_name": "Martin", "surname": "Odegaard",
     "ko_name": "외데고르", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Kai Havertz", "first_name": "Kai", "surname": "Havertz",
     "ko_name": "하베르츠", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Noni Madueke", "first_name": "Noni", "surname": "Madueke",
     "ko_name": "마두에케", "club": "Arsenal",
     "category": "squad", "transfer_status": "in_done"},
    {"full_name": "Ethan Nwaneri", "first_name": "Ethan", "surname": "Nwaneri",
     "ko_name": "은와네리", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Mikel Merino", "first_name": "Mikel", "surname": "Merino",
     "ko_name": "메리노", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Jurrien Timber", "first_name": "Jurrien", "surname": "Timber",
     "ko_name": "팀버", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "David Raya", "first_name": "David", "surname": "Raya",
     "ko_name": "라야", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Riccardo Calafiori", "first_name": "Riccardo", "surname": "Calafiori",
     "ko_name": "칼라피오리", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Oleksandr Zinchenko", "first_name": "Oleksandr", "surname": "Zinchenko",
     "ko_name": "진첸코", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Gabriel Jesus", "first_name": "Gabriel", "surname": "Jesus",
     "ko_name": "제수스", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Eddie Nketiah", "first_name": "Eddie", "surname": "Nketiah",
     "ko_name": "은케티아", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Illan Meslier", "first_name": "Illan", "surname": "Meslier",
     "ko_name": "멜리에", "club": "Arsenal",
     "category": "squad", "transfer_status": "in_done"},
    {"full_name": "Piero Hincapie", "first_name": "Piero", "surname": "Hincapie",
     "ko_name": "인카피에", "club": "Arsenal",
     "category": "squad", "transfer_status": "in_done"},
    {"full_name": "Eberechi Eze", "first_name": "Eberechi", "surname": "Eze",
     "ko_name": "에제", "club": "Arsenal",
     "category": "squad", "transfer_status": "in_done"},
    {"full_name": "Ben White", "first_name": "Ben", "surname": "White",
     "ko_name": "화이트", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Gabriel Magalhaes", "first_name": "Gabriel", "surname": "Magalhaes",
     "ko_name": "마갈량이스", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Gabriel Martinelli", "first_name": "Gabriel", "surname": "Martinelli",
     "ko_name": "마르티넬리", "club": "Arsenal",
     "category": "squad", "transfer_status": "none"},
    {"full_name": "Leandro Trossard", "first_name": "Leandro", "surname": "Trossard",
     "ko_name": "트로사르", "club": "Besiktas",
     "category": "external", "transfer_status": "out_done"},
    {"full_name": "Jakub Kiwior", "first_name": "Jakub", "surname": "Kiwior",
     "ko_name": "키비오르", "club": "Porto",
     "category": "external", "transfer_status": "out_done"},
    {"full_name": "Fabio Vieira", "first_name": "Fabio", "surname": "Vieira",
     "ko_name": "비에이라", "club": "Arsenal",
     "category": "squad", "transfer_status": "out_link"},
    {"full_name": "Ismeal Kabia", "first_name": "Ismeal", "surname": "Kabia",
     "ko_name": "카비아", "club": "Arsenal",
     "category": "squad", "transfer_status": "out_link"},
    {"full_name": "Christos Tzolis", "first_name": "Christos", "surname": "Tzolis",
     "ko_name": "촐리스", "club": "Arsenal",
     "category": "squad", "transfer_status": "in_done"},
    {"full_name": "Viktor Gyokeres", "first_name": "Viktor", "surname": "Gyokeres",
     "ko_name": "요케레스", "club": "Arsenal",
     "category": "squad", "transfer_status": "in_done"},
    {"full_name": "Bruno Guimaraes", "first_name": "Bruno", "surname": "Guimaraes",
     "ko_name": "기마랑이스", "club": "Newcastle",
     "category": "external", "transfer_status": "in_link"},
    {"full_name": "Ezri Konsa", "first_name": "Ezri", "surname": "Konsa",
     "ko_name": "콘사", "club": "Aston Villa",
     "category": "external", "transfer_status": "in_link"},
    {"full_name": "Morgan Rogers", "first_name": "Morgan", "surname": "Rogers",
     "ko_name": "로저스", "club": "Chelsea",
     "category": "external", "transfer_status": "other_club"},
    {"full_name": "Julian Alvarez", "first_name": "Julian", "surname": "Alvarez",
     "ko_name": "알바레스", "club": "Atletico Madrid",
     "category": "external", "transfer_status": "in_link"},
    {"full_name": "Lorenzo Pellegrini", "first_name": "Lorenzo", "surname": "Pellegrini",
     "ko_name": "펠레그리니", "club": "Roma",
     "category": "external", "transfer_status": "none"},
    {"full_name": "Marcus Rashford", "first_name": "Marcus", "surname": "Rashford",
     "ko_name": "래시포드", "club": "Manchester United",
     "category": "external", "transfer_status": "in_link"},
    {"full_name": "Elliot Anderson", "first_name": "Elliot", "surname": "Anderson",
     "ko_name": "앤더슨", "club": "Manchester City",
     "category": "external", "transfer_status": "other_club"},
    {"full_name": "Anthony Gordon", "first_name": "Anthony", "surname": "Gordon",
     "ko_name": "고든", "club": "Newcastle",
     "category": "external", "transfer_status": "in_link"},
    {"full_name": "Sandro Tonali", "first_name": "Sandro", "surname": "Tonali",
     "ko_name": "토날리", "club": "Newcastle",
     "category": "external", "transfer_status": "in_link"},
    {"full_name": "Pierre-Emerick Aubameyang", "first_name": "Pierre-Emerick", "surname": "Aubameyang",
     "ko_name": "오바메양", "club": None,
     "category": "external", "transfer_status": "none"},
    {"full_name": "Kylian Mbappe", "first_name": "Kylian", "surname": "Mbappe",
     "ko_name": "음바페", "club": "Real Madrid",
     "category": "external", "transfer_status": "none"},
    {"full_name": "Jude Bellingham", "first_name": "Jude", "surname": "Bellingham",
     "ko_name": "벨링엄", "club": "Real Madrid",
     "category": "external", "transfer_status": "none"},
]
